CREATE TABLE PRODUCT(
	P_CODE INTEGER AUTO_INCREMENT PRIMARY KEY,
    P_DESCRIPT VARCHAR(35) NOT NULL,
    P_INDATE DATE NOT NULL,
    P_QOH INTEGER NOT NULL,
    P_MIN INTEGER NOT NULL,
    P_PRICE DECIMAL(8,2) NOT NULL,
    P_DISCOUNT DECIMAL(5,2) DEFAULT 0.00 NOT NULL CHECK(P_DISCOUNT BETWEEN 0 AND 1)
);
CREATE TABLE INVENTORY_LOG(
	P_CODE INTEGER NOT NULL REFERENCES PRODUCT(P_CODE),
    LOG_NUMBER INTEGER NOT NULL,
    LOG_DESCRIPT ENUM('RESTOCK', 'RETURN', 'DEFECTIVE', 'ADJUST IN', 'ADJUST OUT') NOT NULL,
    LOG_INDATE DATE NOT NULL,
    LOG_UNITS INTEGER NOT NULL CHECK(LOG_UNITS>0),
    PRIMARY KEY(P_CODE, LOG_NUMBER)
);
CREATE TABLE CUSTOMER(
	CUS_CODE INTEGER AUTO_INCREMENT PRIMARY KEY,
    CUS_NAME VARCHAR(10) NOT NULL,
    CUS_PHONE CHAR(10) NOT NULL,
    CUS_BALANCE DECIMAL(9,2) DEFAULT 0.00
);
CREATE TABLE INVOICE(
	INV_NUMBER INTEGER AUTO_INCREMENT PRIMARY KEY,
    CUS_CODE INTEGER NOT NULL REFERENCES CUSTOMER(CUS_CODE),
    INV_DATE DATETIME DEFAULT NOW() NOT NULL,
    INV_PAYMENT ENUM('CASH', 'CARD', 'BANK_TRANSFER', 'E_WALLET'),
    INV_PAID BOOLEAN NOT NULL DEFAULT 0,
    INV_TRANSCODE VARCHAR(50),
    EMP_CODE INTEGER NOT NULL REFERENCES EMPLOYEE(EMP_CODE)
);
CREATE TABLE LINE(
	INV_NUMBER INTEGER NOT NULL REFERENCES INVOICE(INV_NUMBER) ON DELETE CASCADE,
    LINE_NUMBER DECIMAL(2,0) NOT NULL,
    P_CODE VARCHAR(10) NOT NULL REFERENCES PRODUCT(P_CODE),
    LINE_UNITS INTEGER NOT NULL,
    LINE_PRICE DECIMAL(9,2) NOT NULL,
    PRIMARY KEY(INV_NUMBER, LINE_NUMBER),
    CONSTRAINT UNIQUE(INV_NUMBER, P_CODE)
);
CREATE TABLE EMPLOYEE(
	EMP_CODE INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMP_LNAME VARCHAR(10) NOT NULL,
    EMP_FNAME VARCHAR(10) NOT NULL,
    EMP_JOB VARCHAR(50) NOT NULL
);

ALTER TABLE PRODUCT AUTO_INCREMENT = 100;
ALTER TABLE CUSTOMER AUTO_INCREMENT = 100;
ALTER TABLE INVOICE AUTO_INCREMENT = 1000;
ALTER TABLE EMPLOYEE AUTO_INCREMENT = 100;

CREATE VIEW INVOICE_SUMMARY AS(
SELECT
	INV_NUMBER,
    INV_DATE,
    INV_PAID,
    CUS_CODE,
    CUS_NAME,
    SUM(LINE_UNITS*LINE_PRICE) AS TOTAL_AMOUNT
FROM INVOICE
JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
JOIN CUSTOMER ON INVOICE.CUS_CODE = CUSTOMER.CUS_CODE
GROUP BY INV_NUMBER, INV_DATE, INV_PAID, CUS_CODE, CUS_NAME
);
CREATE VIEW SALES_BY_DAY AS(
SELECT
	DATE(INV_DATE) AS 'DATE',
    COUNT(DISTINCT INV_NUMBER) AS TOTAL_INVOICES,
    SUM(LINE_UNITS*LINE_PRICE) AS TOTAL_SALES
FROM INVOICE JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
GROUP BY DATE(INV_DATE)
);
CREATE VIEW SALES_BY_PRODUCT AS(
SELECT 
	P_CODE,
    P_DESCRIPT,
    P_QOH,
    P_MIN,
    SUM(LINE_UNITS) AS UNITS_SOLD,
    SUM(LINE_UNITS*LINE_PRICE) AS TOTAL_SALES
FROM PRODUCT JOIN LINE ON PRODUCT.P_CODE = LINE.P_CODE
GROUP BY P_CODE, P_DESCRIPT
);
CREATE VIEW SALES_BY_CUSTOMER AS(
SELECT
	CUS_CODE,
    CUS_NAME,
    CUS_BALANCE,
    COUNT(DISTINCT INV_NUMBER) AS TOTAL_INVOICES,
    SUM(LINE_UNITS*LINE_PRICE) AS TOTAL_SALES
FROM CUSTOMER 
JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
GROUP BY CUS_CODE, CUS_NAME, CUS_BALANCE
);
CREATE VIEW SALES_BY_EMPLOYEE AS(
SELECT
	EMP_CODE,
    EMP_NAME,
    COUNT(DISTINCT INV_NUMBER) AS TOTAL_INVOICES,
    SUM(LINE_UNITS*LINE_PRICE) AS TOTAL_SALES
FROM EMPLOYEE 
JOIN INVOICE ON EMPLOYEE.EMP_CODE = INVOICE.EMP_CODE
JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
GROUP BY EMP_CODE, EMP_NAME
);
CREATE VIEW PRODUCT_LOW_STOCK AS(
SELECT 
	P_CODE,
    P_DESCRIPT,
    (P_MIN - P_QOH) AS SHORTAGE
FROM PRODUCT
WHERE P_QOH < P_MIN
);
CREATE VIEW INVOICE_UNPAID AS(
SELECT 
	INV_NUMBER,
    INV_DATE,
    CUS_CODE,
    CUS_NAME,
    SUM(LINE_UNITS*LINE_PRICE) AS TOTAL_AMOUNT
FROM INVOICE
JOIN CUSTOMER ON INVOICE.CUS_CODE = CUSTOMER.CUS_CODE
JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
WHERE INV_PAID = 0
GROUP BY INV_NUMBER, INV_DATE, CUS_CODE, CUS_NAME
);

CREATE INDEX IDX_P_DESCRIPT ON PRODUCT(P_DESCRIPT);
CREATE UNIQUE INDEX IDX_CUS_PHONE ON CUSTOMER(CUS_PHONE);
CREATE INDEX IDX_INVOICE_CUSTOMER ON INVOICE(CUS_CODE);
CREATE INDEX IDX_INV_DATE ON INVOICE(INV_DATE);
CREATE INDEX LINE_X ON LINE(P_CODE);

DELIMITER //
CREATE FUNCTION LINE_TOTAL_AMOUNT(
	inv_number INTEGER, 
    line_number DECIMAL(2,0)) 
RETURNS DECIMAL(9,2) DETERMINISTIC READS SQL DATA
BEGIN
	SELECT LINE_UNIT*LINE_PRICE
    FROM LINE 
    WHERE LINE.INV_NUMBER = inv_number AND LINE.LINE_NUMBER = line_number;
END;//
CREATE FUNCTION INVOICE_TOTAL_AMOUNT(
	inv_number INTEGER) 
RETURNS DECIMAL(9,2) DETERMINISTIC READS SQL DATA
BEGIN
	SELECT SUM(LINE_UNITS*LINE_PRICE)
    FROM LINE
    WHERE LINE.INV_NUMBER = inv_number;
END;//

CREATE PROCEDURE CREATE_INVOICE(
	IN cus_code INTEGER, 
    IN p_code INTEGER, 
    IN line_units INTEGER,
    IN emp_code INTEGER)
BEGIN
	DECLARE line_price DECIMAL(9,2);
    DECLARE inv_number INTEGER;
    DECLARE total_amount DECIMAL(9,2);
    
    INSERT INTO INVOICE(CUS_CODE, INV_DATE, INV_PAYMENT, INV_PAID, INV_TRANSCODE, EMP_CODE) 
    VALUES(cus_code, NOW(), NULL, 0, NULL, emp_code);
    SELECT LAST_INSERT_ID() INTO inv_number;
    
    SELECT P_PRICE*(1 - P_DISCOUNT) INTO line_price 
    FROM PRODUCT WHERE  P_CODE = p_code;
    INSERT INTO LINE VALUES(inv_number, 1, p_code, line_units, line_price);
    
    SET total_amount = INVOICE_TOTAL_AMOUNT(inv_number);
    UPDATE CUSTOMER 
    SET CUS_BALANCE = CUS_BALANCE + total_amount
    WHERE CUS_CODE = cus_code;
    
    SELECT inv_number AS INV_NUMBER, total_amount as TOTAL_AMOUNT;
END;//
 CREATE PROCEDURE CREATE_LINE(
	IN inv_number INTEGER, 
    IN line_number DECIMAL(2,0), IN p_code INTEGER, 
    IN line_units INTEGER)
 BEGIN
	DECLARE line_price DECIMAL(9,2);
    
    IF (SELECT INV_PAID FROM INVOICE WHERE INV_NUMBER = inv_number) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'CANNOT ADD LINES TO A PAID INVOICE';
	END IF;
    
    SELECT P_PRICE*(1 - P_DISCOUNT) INTO line_price 
    FROM PRODUCT WHERE P_CODE = p_code;
	INSERT INTO LINE VALUES(inv_number, line_number, p_code, line_units, line_price);
    
    UPDATE CUSTOMER 
    SET CUS_BALANCE = CUS_BALANCE + LINE_TOTAL_AMOUNT(inv_number, line_number)
    WHERE CUS_CODE = (SELECT CUS_CODE FROM INVOICE WHERE INV_NUMBER = inv_number);
    SELECT 
		inv_number as INV_NUMBER, 
		COUNT(*) AS TOTAL_PRODUCTS,
        INVOICE_TOTAL_AMOUNT(inv_number)
	FROM LINE WHERE INV_NUMBER = inv_number;
END;//
CREATE PROCEDURE REGISTER_PAYMENT(
	IN inv_number INTEGER, 
    IN inv_payment ENUM('CASH', 'CARD', 'BANK_TRANSFER', 'E_WALLET'), 
    IN inv_transcode VARCHAR(50))
BEGIN
	IF NOT EXISTS (SELECT * FROM INVOICE WHERE INV_NUMBER = inv_number) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'INVOICE DOES NOT EXISTS';
	END IF;
	
    IF (SELECT INV_PAID FROM INVOICE WHERE INV_NUMBER = inv_number) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'INVOICE IS ALREADY PAID';
	END IF;
        
	UPDATE INVOICE
    SET INV_PAYMENT = inv_payment, INV_PAID = 1, INV_TRANSCODE = inv_transcode
    WHERE INV_NUMBER = inv_number;
    
    UPDATE CUSTOMER
    SET CUS_BALANCE = CUS_BALANCE - INVOICE_TOTAL_AMOUNT(inv_number)
    WHERE CUSTOMER.CUS_CODE = (SELECT CUS_CODE FROM INVOICE WHERE INV_NUMBER = inv_number);
    
    SELECT INV_NUMBER, INV_PAYMENT, INV_PAID, INV_TRANSCODE
    FROM INVOICE WHERE INV_NUMBER = inv_number;
END;//

CREATE TRIGGER CHECK_STOCK BEFORE INSERT ON LINE FOR EACH ROW 
BEGIN
    IF NEW.LINE_UNITS < (SELECT P_QOH FROM PRODUCT WHERE P_CODE = NEW.P_CODE) THEN 
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NOT ENOUGH STOCK AVAILABLE';
	END IF;
END;//
CREATE TRIGGER REDUCE_STOCK AFTER INSERT ON LINE FOR EACH ROW 
BEGIN
	UPDATE PRODUCT
    SET P_QOH = P_QOH - NEW.LINE_UNITS
    WHERE P_CODE = NEW.P_CODE;
END;//
CREATE TRIGGER RESTORE_STOCK AFTER DELETE ON LINE FOR EACH ROW 
BEGIN
	UPDATE PRODUCT
    SET P_QOH = P_QOH + OLD.LINE_UNITS
    WHERE P_CODE = OLD.P_CODE;
END;//
CREATE TRIGGER RESTOCK_PRODUCT AFTER INSERT ON INVENTORY_LOG FOR EACH ROW 
BEGIN
	IF NEW.LOG_TYPE = 'DEFECTIVE' OR NEW.LOG_TYPE = 'ADJUST OUT' THEN
		UPDATE PRODUCT
		SET P_QOH = P_QOH - NEW.LOG_UNITS
		WHERE PRODUCT.P_CODE = NEW.P_CODE;
	ELSE
		UPDATE PRODUCT
		SET P_QOH = P_QOH + NEW.LOG_UNITS
		WHERE PRODUCT.P_CODE = NEW.P_CODE;
	END IF;
END;//
CREATE TRIGGER CHECK_TRANSCODE BEFORE INSERT ON INVOICE FOR EACH ROW 
BEGIN
	IF NEW.INV_PAID = 0 THEN
		IF NEW.INV_PAYMENT IS NOT NULL OR NEW.INV_TRANSCODE IS NOT NULL THEN
			SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'UNPAID INVOICE HAVE NO PAYMENT METHOD OR TRANSCODE';
            END IF;
    ELSE
		IF NEW.INV_PAYMENT IS NULL THEN
			SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'PAID INVOICE MUST HAVE PAYMENT METHOD';
			END IF;
        IF NEW.INV_PAYMENT = 'CASH' AND NEW.INV_TRANSCODE IS NOT NULL THEN
			SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'CASH PAYMENT HAVE NO TRANSACTION CODE';
			END IF;
        IF NEW.INV_PAYMENT <> 'CASH' AND NEW.INV_TRANSCODE IS NULL THEN
			SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'NONCASH PAYMENT MUST HAVE TRANSACTION CODE';
			END IF;
    END IF;
END;//
CREATE TRIGGER CHECK_TRANSCODE BEFORE UPDATE ON INVOICE FOR EACH ROW 
BEGIN
	IF NEW.INV_PAID = 0 THEN
		IF NEW.INV_PAYMENT IS NOT NULL OR NEW.INV_TRANSCODE IS NOT NULL THEN
			SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'UNPAID INVOICE HAVE NO PAYMENT METHOD OR TRANSCODE';
            END IF;
    ELSE
		IF NEW.INV_PAYMENT IS NULL THEN
			SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'PAID INVOICE MUST HAVE PAYMENT METHOD';
			END IF;
        IF NEW.INV_PAYMENT = 'CASH' AND NEW.INV_TRANSCODE IS NOT NULL THEN
			SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'CASH PAYMENT HAVE NO TRANSACTION CODE';
			END IF;
        IF NEW.INV_PAYMENT <> 'CASH' AND NEW.INV_TRANSCODE IS NULL THEN
			SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'NONCASH PAYMENT MUST HAVE TRANSACTION CODE';
			END IF;
		END IF;
END;//
DELIMITER ;;